### ISSUE TITLE
Single month off with revert

### ISSUE THREAD

**Issue by katiesteckles** [christianp/mathsjam-site#2]
Can it be possible to automatically set a MathsJam as being not happening for a particular month, and automatically come back the following month? It would need to update the page for that city with a line to explain, and remove the 'next jam' date from that page; update the front page list of happening jams; and after that month's MathsJam date has passed, change everything back

**Comment by christianp** [comment]
Done! Add `hiatus_months` to the frontmatter, in YYYY-MM format.

For example:

    hiatus: False
    hiatus_months:
         - 2017-01
