### ISSUE TITLE
List of Jams for Monthly Email

### ISSUE THREAD

**Issue by katiesteckles** [christianp/mathsjam-site#6]
This just occurred to me - when i add a new jam to the site, I update a google spreadsheet which is  where I get the list of email addresses to send the monthly shout to from. Could this list be kept by the website and updated, and somewhere I can copy it from to paste when I send the email?

**Comment by christianp** [comment]
Yes it could!

**Comment by christianp** [comment]
What format should the list be in?

**Comment by christianp** [comment]
I've made a comma-separated list in a text file: https://www.checkmyworking.com/misc/new-mathsjam/emails.txt
